# Generated by Django 4.2.13 on 2024-06-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='car',
            name='lastname',
        ),
        migrations.AddField(
            model_name='car',
            name='carNo',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
