# Generated by Django 4.2.13 on 2024-06-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_remove_car_firstname_remove_car_lastname_car_carno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='carNo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
