# Generated by Django 4.2.13 on 2024-06-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_role_alter_car_carno_alter_car_color_alter_car_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(max_length=200)),
            ],
        ),
    ]
