# Generated by Django 4.2.13 on 2024-06-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='slot',
            name='date',
            field=models.DateField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='time',
            field=models.TimeField(max_length=200, null=True),
        ),
    ]
