# Generated by Django 4.2.13 on 2024-06-16 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('slotId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.slot')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.user')),
            ],
        ),
    ]
