# Generated by Django 4.2.13 on 2024-06-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_carslot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarSlot',
            new_name='Appointment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
