# Generated by Django 4.2.13 on 2024-06-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_rename_carslot_appointment_remove_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
